const {EntitySchema} = require("typeorm")

const User = new EntitySchema({
    name: "User", //Entity name
    tableName: "users", //Name of table in database
    columns: {
        id: {
            type: "int", //its an integer
            primary: true, //PRIMARY KEY
            generated: true, //it is autogenerated
            generationStrategy: "increment" //SERIAL
        },
        name: {
            type: "varchar", //VARCHAR          
            length: 100, //(100)
            nullable: false //NOT NULL
        },
        email: {
            type: "varchar", //VARCHAR          
            length: 150, //(150)
            unique: true, //UNIQUE
            nullable: false //NOT NULL
        },
        password: {
            type: "varchar", //VARCHAR          
            length: 100, //(100)
            nullable: false, //NOT NULL
            select: false
        }
    },
    relations: {
        tasks: {
            type: "one-to-many", //One user to many tasks
            target: "Task", // The task entity
            inverseSide: "user" // the user relation on task.js
        }
    }
})

module.exports =  User